# Generated by Django 6.0.4 on 2026-04-13 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('CLAIMED', 'Claimed')], default='LOST', max_length=10)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('BOOKS', 'Books & Notebooks'), ('ID_CARD', 'ID Cards & Wallets'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('location', models.CharField(help_text='Where was it lost or found?', max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
